spring:
  application:
    name: guestbook-service
  zipkin:
    baseUrl: http://zipkin:9411/
  data:
    rest:
      base-path: /api
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/app?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B9:00&rewriteBatchedStatements=true&autoReconnect=true
    username: guest
    password: guest
    test-on-borrow: true
    validation-query: SELECT 1
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      generate-ddl: true
      ddl-auto: create-drop
      globally_quoted_identifiers: true
  sleuth:
    sampler:
      percentage: "1.0"