apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-service
  labels:
    app: guestbook-service
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-service
      serving: "true"
  template:
    metadata:
      labels:
        app: guestbook-service
        version: "latest"
        serving: "true"
        visualize: "true"
      annotations:
        visualizer/uses: mysql
    spec:
      containers:
      - name: guestbook-service
        image: shinyay/spring-sleuth-mysql-app:latest
        ports:
        - name: http
          containerPort: 8080
