spring:
  application:
    name: backend-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://zipkin:9411/
greeting: Hello $name from $hostname with $version
version: 1.0
