apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-file
data:
  my.cnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    character-set-server=utf8mb4

    [client]
    default-character-set=utf8mb4
